#+TITLE: DoMiNeLa10's .emacs

* About this .emacs
This is my config for GNU Emacs. out won't work with GNU Emacs 24 and older
versions. Tables with customized keybindings are [[file:documentation/changed-keybindings.org][here]].

If you want to reuse any of my own code from this repository, feel free to do
it. I'd appreciate comments linking to my repository before function
definitions from here, but they're not necessary. I didn't put any license on
this repository to avoid possible conflicts with extensions.

* Untracked directories for local configuration
I hold my settings specific to my Arch installation in
=~/.emacs.d/config/my-local.el=. You can put your own customizations there if
you want to use my config. Files in =~/.emacs.d/lisp/local/= are ignored too.

Use =M-x my-update-autoloads= to build autoload files for them automatically.
Extensions come with byte compiled files, so they can work faster and they're
loaded using autoload files so that Emacs can start up faster.

* This config is used on these operating systems:
- [[https://www.archlinux.org/][Arch GNU/Linux]]
- Android 5.0 with [[https://termux.com/][Termux]] (wasn't tested in a while)
- Multiple versions of Windows (using the native build from the [[https://www.gnu.org/software/emacs/download.html#windows][GNU FTP]])

* Installation:
On Unix-like operating systems such as GNU/Linux and on Termux:
#+BEGIN_EXAMPLE
cd ~
git clone https://github.com/DoMiNeLa10/.emacs.d.git
#+END_EXAMPLE
You can update this config with =git pull=.

Make sure you don't have a file named =.emacs= in your home directory, because
it overrides =~/.emacs.d/init.el=.

If you are on Windows NT, copy =.emacs.d= to =%appdata%=. You'll need to set
up the =HOME= environment variable on older versions of Windows, and copy this
config there.

If you can't use git for some reason, you can use GitHub's “download ZIP”
feature. You'll have to rename the folder that will be in the zip file,
because GitHub puts the name of the branch after the name of the repository.

* Structure of directories in this repo
** this directory
- =init.el= :: The first file from this repo that is loaded. It only contains
     code that loads other files. No customizations should go in there.
- =README.org= :: This file.

*** =config=
- =my-customization.el= :: Contains basic general Emacs customization, and
     customization for modes that come with it out of the box.
- =my-defuns.el= :: Definitions of custom functions (in this case ones that
     use default dynamic scoping.)
- =my-extensions.el= :: Customization for added extensions.
- =my-indentation.el= :: Indentation settings.
- =my-lexical.el= :: Definitions of functions that rely on lexical scoping.
     Mostly functions that generate closures.
- =my-local.el= :: Untracked file for installation-specific settings.
- =my-local-variables.el= :: Defines safe file local variables and their
     values.

*** =documentation=
This directory contains =.org= files with additional documentation. More files
might be added to it in the future.

- =changed-keybindings.org= :: Tables listing changed keybindings.

*** =lisp=
This directory contains Emacs lisp source code files, byte-compiled versions
of them. Some extensions have more than one file, and they go to their own
directories.

=autoloads.el= is created automatically in every directory with
=my-update-autoloads=. These files exist to speed up startup of Emacs.

The =local= directory is intentionally untracked. Emacs lisp code can go there
if needed.

* Links to extensions included in this config:
- [[https://github.com/skeeto/impatient-mode][impatient-mode]] :: live preview of buffers in a browser
- [[https://github.com/skeeto/emacs-web-server][simple-httpd]] :: httpd in pure Emacs lisp
- [[https://melpa.org/#/htmlize][htmlize]] :: turns Emacs buffers into HTML with syntax highlighting
- [[https://github.com/fxbois/web-mode][web-mode]] [[https://github.com/DoMiNeLa10/web-mode][(my fork)]] :: major mode for editing HTML files with syntax
     highlighting for inline CSS and JavaScript
- [[https://github.com/DoMiNeLa10/ox-sfhp][ox-sfhp]] :: exports org-mode files to simple single file HTML presentations
- [[https://github.com/mooz/js2-mode][js2-mode]] :: improved JavaScript major mode
