;;; `straight' configuration
(setq straight-cache-autoloads t)

;; github packages
(mapc
 #'my-straight-require-from-github
 '(("joaotavora/yasnippet")
   ("gonewest818/dimmer.el" dimmer)
   ("hniksic/emacs-htmlize" htmlize)
   ("bbatsov/projectile")
   ("company-mode/company-mode" company)
   ("minad/cape")
   ("Fuco1/smartparens")
   ("magit/magit")
   ("UwUnyaa/presentation-mode")
   ("UwUnyaa/ox-reveal")
   ("UwUnyaa/ox-sfhp")
   ("larstvei/ox-gfm")
   ("skeeto/emacs-http-server" simple-httpd)
   ("ledger/ledger-mode")
   ("mooz/js2-mode")
   ("felipeochoa/rjsx-mode")
   ("ananthakumaran/tide")
   ("emacs-php/php-mode")
   ("rust-lang/rust-mode")
   ("Emacs-D-Mode-Maintainers/Emacs-D-Mode" d-mode)
   ("fxbois/web-mode")
   ("UwUnyaa/web-mode-plus")
   ("UwUnyaa/json-mode")
   ("ljos/jq-mode")
   ("pashky/restclient.el" restclient)
   ("alf/ob-restclient.el" ob-restclient)
   ("spotify/dockerfile-mode")
   ("yoshiki/yaml-mode")
   ("jrblevin/markdown-mode")
   ("Fanael/edit-indirect")
   ("purcell/exec-path-from-shell")
   ("haskell/haskell-mode")
   ("preetpalS/emacs-dotenv-mode" dotenv-mode)
   ("emacsmirror/csv-mode")
   ("emacsorphanage/haxe-mode")))
